#!/bin/bash
# Runs train_cmu script iteratively with error handling

START=$1

if [ -z $2 ]; then
    END=9999
else
    END=$2
fi

git pull && ./scripts/clear_nvidia_cache

epoch=$START
while [ $epoch -le $END ]
do
    git pull && ./scripts/clear_nvidia_cache

    TIMESTAMP_START=`date +%Y-%m-%d_%H-%M-%S`
    ./scripts/train_cmu 3 || {
        cd ./logs/cmu/train
        ./change_checkpoints "cmu_vol_softmax_VolumetricTriangulationNet@*" $epoch

        TIMESTAMP_END=`date +%Y-%m-%d_%H-%M-%S`
        echo "Epoch $epoch complete! Time: $TIMESTAMP_START $TIMESTAMP_END" >> ~/.messages # | write $WRITE_TO_USER
        cd -
    }

    ((epoch = epoch + 1))
done